lib/mayor_game_web/router.ex
defmodule MayorGameWeb.Router do
  use MayorGameWeb, :router
  # Pow route macros
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword, PowPersistentSession, PowEmailConfirmation]

  # create pipeline for general browser
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    # :put_root_layout ensures that LiveView layouts and plain Phoenix layouts use a common template as their basis.
    plug :put_root_layout, {MayorGameWeb.LayoutView, :root}
  end

  # add pipeline for protected resources
  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # customize registrationController?
  # actually first let me just try doing this on the homepage
  # scope "/", Pow.Phoenix, as: "pow" do
  #   pipe_through :browser

  #   post "/sign_up", RegistrationController, :create
  # end

  scope "/" do
    pipe_through :browser

    # honestly no idea what this is doing
    # maybe this is what's giving the @current_user in the conn to /?
    pow_routes()
    pow_extension_routes()
  end

  scope "/", MayorGameWeb do
    pipe_through :browser

    get "/", PageController, :index
    live "/market", MarketLive
    live "/city/:title", CityLive, as: :city
    live "/city/:title/logs", LogsLive, as: :city

    # Line Added
    # resources "/verify-email", VerificationController, singleton: true, only: [:show]
    # Line Added
    # resources "/confirm-email", ConfirmationController, only: [:show]

    # get "/cities/:town_id/users/:user_id", CityController, :index
  end

  # Make city routes protected by requiring authentication
  # don't need to do this tho
  scope "/", MayorGameWeb do
    pipe_through [:browser, :protected]

    # don't think we made this yet
    # resources "/cities", CityController

    post "/registration/send-confirmation-email", RegistrationController, :resend_confirmation_email
  end

  # Other scopes may use custom stacks.
  # scope "/api", MayorGameWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MayorGameWeb.Telemetry
    end
  end
end

lib/mayor_game_web/views/layout_view.ex
defmodule MayorGameWeb.LayoutView do
  use MayorGameWeb, :view
end

lib/mayor_game_web/templates/layout/app.html.eex
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<%= @inner_content %>

lib/mayor_game_web/templates/layout/live.html.leex
<p class="alert alert-info" role="alert"><%= live_flash(@flash, :notice) %></p>
<p class="alert alert-danger" role="alert"><%= live_flash(@flash, :error) %></p>
<%= @inner_content %>

lib/mayor_game_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-XJE5DTH2CE"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-XJE5DTH2CE');
  </script>

    <%= csrf_meta_tag() %>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>fragile.city</title>
    <%= if Application.get_env(:mayor_game, :env) == :dev do %>
      <link rel="icon" type="image/x-icon" href="/images/favicon_dev.ico">
    <% else %>
      <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <% end %>

    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/assets/app.css") %>"/>
    <script phx-track-static defer type="text/javascript" src="<%= Routes.static_path(@conn, "/assets/app.js") %>"></script>
  </head>
  <body class="text-sm bg-amber-50 h-screen flex flex-col">
    <header class="border-b border-neutral-800 bg-amber-50 w-screen z-20 py-1 px-2">
        <nav role="navigation">
          <ul class="flex flex-row space-x-3 items-center h-full">
            <li class="hover:underline mr-auto"><a href="<%= Routes.static_path(@conn, "/") %>">fragile.city</a></li>
            <li class="hover:underline"><a href="<%= Routes.static_path(@conn, "/market") %>">Market</a></li>
            <li class="hover:underline"><a href="https://patreon.com/user?u=88349213" target="_blank">Patreon</a></li>
            <li class="hover:underline"><a href="https://fragile-city.notion.site/Intro-25d07a8aade7459a9b2a93429170b29b" target="_blank">FAQ</a></li>
            <%= if Pow.Plug.current_user(@conn) do %>

              <%= if is_nil(Pow.Plug.current_user(@conn).email_confirmed_at) do %>
                <li class="hover:underline"><%= link("Verify Email", to: Routes.registration_path(@conn, :resend_confirmation_email), method: :post) %></li>
              <% end %>

              <li class="hover:underline"><a href="https://discord.gg/mnVnRdV3k7" target="_blank">Discord</a></li>
              <li class="hover:underline"><%= link "Profile", to: Routes.pow_registration_path(@conn, :edit) %></li>
              <li class="hover:underline"><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></li>
            <% else %>
              <li class="hover:underline"><%= link "Register", to: Routes.pow_registration_path(@conn, :new) %></li>
              <li class="hover:underline"><%= link "Sign in", to: Routes.pow_session_path(@conn, :new) %></li>
            <% end %>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li class="hover:underline"><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
    </header>
    <main role="main" class="flex-grow overflow-y-scroll" >
      <%= @inner_content %>
    </main>
  </body>

</html>